# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5e163909472041c72d0c98838f5bc1e303246233b0c3d27e349816cb29496f03f5f3ed2d7f46aebdcbb8073fd84e97512390ed153264db1f8cc07bea0e75f1c

test:
  secret_key_base: f6284b97eab4fd980b9c927a325d9c159d52ae6ec27a7d5bf1b4ac04d1ecca22ac02750e655d09dd2cd21fdbc43dffd6ed9801db499f72fab03f1d9bfbaeab14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
